# Configuração do Tema
theme: jekyll-theme-minimal
title: VoxAI
description: Assistente de Apoio e Informação LGBTQIA+

exclude:
  - .devcontainer/
  - .github/
  - .streamlit/
  - data/
  - scripts/
  - src/
  - static/
  - .gitignore
  - requirements.txt
  - startup_patch.py
  - vox_ai.py